In [7]:
import certifi
import json
import pandas as pd
from urllib.request import urlopen

In [8]:
pd.set_option("display.max_columns", 100)

### Load balance sheet info

In [12]:
url_balance_sheet = "https://financialmodelingprep.com/api/v3/balance-sheet-statement/TIMA?period=quarter&from=2018-12-31&to=2019-12-31"
response_balance_sheet = urlopen(url_balance_sheet, cafile=certifi.where())
data_balance_sheet = response_balance_sheet.read().decode("utf-8")
data_balance_sheet = json.loads(data_balance_sheet)

/var/folders/mr/pm_1h_jn1gs2n48rx1j1ygsr0000gn/T/ipykernel_96777/1921437915.py:2: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.
  response_balance_sheet = urlopen(url_balance_sheet, cafile=certifi.where())

In [13]:
data_balance_sheet

[]

In [10]:
balance_sheet_df = pd.DataFrame(data_balance_sheet)
balance_sheet_df = balance_sheet_df.set_index("date")
balance_sheet_df

ValueError: If using all scalar values, you must pass an index

In [59]:
balance_sheet_df.tail()

,symbol_bs,reportedCurrency_bs,cik_bs,fillingDate_bs,acceptedDate_bs,calendarYear_bs,period_bs,cashAndCashEquivalents_bs,shortTermInvestments_bs,cashAndShortTermInvestments_bs,netReceivables_bs,inventory_bs,otherCurrentAssets_bs,totalCurrentAssets_bs,propertyPlantEquipmentNet_bs,goodwill_bs,intangibleAssets_bs,goodwillAndIntangibleAssets_bs,longTermInvestments_bs,taxAssets_bs,otherNonCurrentAssets_bs,totalNonCurrentAssets_bs,otherAssets_bs,totalAssets_bs,accountPayables_bs,shortTermDebt_bs,taxPayables_bs,deferredRevenue_bs,otherCurrentLiabilities_bs,totalCurrentLiabilities_bs,longTermDebt_bs,deferredRevenueNonCurrent_bs,deferredTaxLiabilitiesNonCurrent_bs,otherNonCurrentLiabilities_bs,totalNonCurrentLiabilities_bs,otherLiabilities_bs,capitalLeaseObligations_bs,totalLiabilities_bs,preferredStock_bs,commonStock_bs,retainedEarnings_bs,accumulatedOtherComprehensiveIncomeLoss_bs,othertotalStockholdersEquity_bs,totalStockholdersEquity_bs,totalEquity_bs,totalLiabilitiesAndStockholdersEquity_bs,minorityInterest_bs,totalLiabilitiesAndTotalEquity_bs,totalInvestments_bs,totalDebt_bs,netDebt_bs,link_bs,finalLink_bs
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1990-12-31,SSY,USD,0000096793,1990-12-31,1990-12-31 00:00:00,1991,Q2,1700000,0,1700000,25600000,9500000,700000,37500000,4800000,0,0,0,0,0,6100000,10900000,0,48400000,9100000,14500000,0,0,11200000,34800000,600000,0,3200000,700000,4500000,0,0,39300000,0,0,2700000,0,6400000,9100000,9100000,48400000,0,48400000,0,15100000,13400000,None,None
1990-03-31,SSY,USD,0000096793,1990-03-31,1990-03-31 00:00:00,1990,Q3,300000,0,300000,21500000,7800000,3000000,32600000,4600000,0,0,0,0,0,5300000,9900000,0,42500000,0,19200000,0,0,15300000,34500000,700000,0,1000000,500000,2200000,0,0,36700000,0,0,900000,0,4900000,5800000,5800000,42500000,0,42500000,0,19900000,19600000,None,None
1989-03-31,SSY,USD,0000096793,1989-03-31,1989-03-31 00:00:00,1989,Q3,300000,0,300000,19800000,6700000,15400000,42200000,4900000,0,0,0,0,0,4800000,9700000,0,51900000,0,20300000,0,0,13000000,33300000,6800000,0,100000,400000,7300000,0,0,40600000,0,0,6000000,0,5300000,11300000,11300000,51900000,0,51900000,0,27100000,26800000,None,None
1988-03-31,SSY,USD,0000096793,1988-03-31,1988-03-31 00:00:00,1988,Q3,800000,0,800000,35000000,29000000,1300000,66100000,12300000,0,0,0,0,0,600000,12900000,0,79000000,0,2300000,0,0,47200000,49500000,9500000,0,500000,2600000,12600000,0,0,62100000,0,0,7100000,0,9800000,16900000,16900000,79000000,0,79000000,0,11800000,11000000,None,None
1987-03-31,SSY,USD,0000096793,1987-03-31,1987-03-31 00:00:00,1987,Q3,300000,0,300000,26600000,27700000,800000,55400000,9500000,0,0,0,0,0,500000,10000000,0,65400000,0,1700000,0,0,40200000,41900000,7700000,0,200000,2000000,9900000,0,0,51800000,0,0,6700000,0,6900000,13600000,13600000,65400000,0,65400000,0,9400000,9100000,None,None

### Load income stmt info

In [5]:
url_income_stmt = "https://financialmodelingprep.com/api/v3/income-statement/SSY?period=quarter&from=2018-12-31&to=2019-12-31"
response_income_stmt = urlopen(url_income_stmt, cafile=certifi.where())
data_income_stmt = response_income_stmt.read().decode("utf-8")
data_income_stmt = json.loads(data_income_stmt)

/var/folders/mr/pm_1h_jn1gs2n48rx1j1ygsr0000gn/T/ipykernel_98401/1617978485.py:2: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.
  response_income_stmt = urlopen(url_income_stmt, cafile=certifi.where())

In [6]:
income_stmt_df = pd.DataFrame(data_income_stmt)
income_stmt_df = income_stmt_df.set_index("date")
income_stmt_df

,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,otherExpenses,operatingExpenses,costAndExpenses,interestIncome,interestExpense,depreciationAndAmortization,ebitda,ebitdaratio,operatingIncome,operatingIncomeRatio,totalOtherIncomeExpensesNet,incomeBeforeTax,incomeBeforeTaxRatio,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-03-31,SSY,USD,0000096793,2023-05-10,2023-05-10 16:40:35,2023,Q3,11533000,6066000,5467000,0.474031,0,4656000,0,4656000,1585000,6241000,12307000,0,41000,414000,-360000,-0.031215,-774000,-0.067112,41000,-733000,-0.063557,-6000,-727000,-0.063037,-0.10,-0.10,7032000,7032000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-12-31,SSY,USD,0000096793,2023-02-14,2023-02-14 11:34:09,2023,Q2,14392000,5918000,8474000,0.588799,0,4793000,0,4793000,1641000,6434000,12352000,0,9000,385000,2425000,0.168496,2040000,0.141745,11000,2051000,0.142510,-1000,1951000,0.135561,0.28,0.28,7031000,7033000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-09-30,SSY,USD,0000096793,2022-11-14,2022-11-14 13:14:19,2023,Q1,11037000,5741000,5296000,0.479841,0,5448000,0,5448000,1461000,6909000,12650000,0,-4000,356000,-1257000,-0.113890,-1613000,-0.146145,69000,-1544000,-0.139893,-63000,-1481000,-0.134185,-0.21,-0.21,6983000,6983000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-06-30,SSY,USD,0000096793,2022-09-28,2022-09-28 14:55:21,2022,Q4,9881000,5581000,4300000,0.435179,0,4916000,0,4916000,1595000,6511000,12092000,0,3000,462000,-1749000,-0.177006,-2211000,-0.223763,1000,-2210000,-0.223662,107000,-2317000,-0.234490,-0.33,-0.33,6945000,6945000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-03-31,SSY,USD,0000096793,2022-05-16,2022-05-16 16:17:02,2022,Q3,10527000,5315000,5212000,0.495108,0,4865000,0,4865000,1411000,6276000,11591000,0,-14000,384000,-680000,-0.064596,-1064000,-0.101073,105000,-959000,-0.091099,-25000,-934000,-0.088724,-0.13,-0.13,6954000,6954000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986-12-31,SSY,USD,0000096793,1986-12-31,1986-12-31 00:00:00,1987,Q2,29600000,0,29600000,1.000000,0,0,0,0,0,0,0,0,0,0,29600000,1.000000,29600000,1.000000,0,0,0.000000,0,0,0.000000,0.00,0.00,4779000,4779000,None,None
1986-09-30,SSY,USD,0000096793,1987-03-31,1986-09-30 00:00:00,1987,Q1,28300000,-3500000,31800000,1.123675,0,0,0,0,-122500000,-122500000,-126000000,0,0,119000000,28300000,1.000000,-90700000,-3.204947,0,0,0.000000,0,0,0.000000,0.00,0.00,4431000,4431000,None,None
1986-06-30,SSY,USD,0000096793,1986-06-30,1986-06-30 00:00:00,1986,Q4,29700000,0,29700000,1.000000,0,0,0,0,0,0,0,0,0,0,29700000,1.000000,29700000,1.000000,0,0,0.000000,0,0,0.000000,0.00,0.00,4375000,4375000,None,None
1985-12-31,SSY,USD,0000096793,1985-12-31,1985-12-31 00:00:00,1986,Q2,33000000,0,33000000,1.000000,0,0,0,0,0,0,0,0,0,0,33000000,1.000000,33000000,1.000000,0,0,0.000000,0,0,0.000000,0.00,0.00,4375000,4375000,None,None
1985-09-30,SSY,USD,0000096793,1985-09-30,1985-09-30 00:00:00,1986,Q1,27100000,0,27100000,1.000000,0,0,0,0,0,0,0,0,0,0,27100000,1.000000,27100000,1.000000,0,0,0.000000,0,0,0.000000,0.00,0.00,4375000,4375000,None,None

In [60]:
income_stmt_df.tail()

,revenue_is,costOfRevenue_is,grossProfit_is,grossProfitRatio_is,researchAndDevelopmentExpenses_is,generalAndAdministrativeExpenses_is,sellingAndMarketingExpenses_is,sellingGeneralAndAdministrativeExpenses_is,otherExpenses_is,operatingExpenses_is,costAndExpenses_is,interestIncome_is,interestExpense_is,depreciationAndAmortization_is,ebitda_is,ebitdaratio_is,operatingIncome_is,operatingIncomeRatio_is,totalOtherIncomeExpensesNet_is,incomeBeforeTax_is,incomeBeforeTaxRatio_is,incomeTaxExpense_is,netIncome_is,netIncomeRatio_is,eps_is,epsdiluted_is,weightedAverageShsOut_is,weightedAverageShsOutDil_is
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1986-12-31,29600000,0,29600000,1.000000,0,0,0,0,0,0,0,0,0,0,29600000,1.0,29600000,1.000000,0,0,0.0,0,0,0.0,0.0,0.0,4779000,4779000
1986-09-30,28300000,-3500000,31800000,1.123675,0,0,0,0,-122500000,-122500000,-126000000,0,0,119000000,28300000,1.0,-90700000,-3.204947,0,0,0.0,0,0,0.0,0.0,0.0,4431000,4431000
1986-06-30,29700000,0,29700000,1.000000,0,0,0,0,0,0,0,0,0,0,29700000,1.0,29700000,1.000000,0,0,0.0,0,0,0.0,0.0,0.0,4375000,4375000
1985-12-31,33000000,0,33000000,1.000000,0,0,0,0,0,0,0,0,0,0,33000000,1.0,33000000,1.000000,0,0,0.0,0,0,0.0,0.0,0.0,4375000,4375000
1985-09-30,27100000,0,27100000,1.000000,0,0,0,0,0,0,0,0,0,0,27100000,1.0,27100000,1.000000,0,0,0.0,0,0,0.0,0.0,0.0,4375000,4375000

### Manipulate balance sheet & income stmt columns

In [8]:
# these columns appear both in the balance sheet and in the income statement
income_stmt_cols_to_drop = [
    "symbol",
    "reportedCurrency",
    "cik",
    "fillingDate",
    "acceptedDate",
    "calendarYear",
    "period",
    "finalLink",
    "link",
]

In [9]:
income_stmt_df = income_stmt_df.drop(columns=income_stmt_cols_to_drop, axis=1)

In [10]:
balance_sheet_df.columns = [col+"_bs" for col in balance_sheet_df.columns]
income_stmt_df.columns = [col+"_is" for col in income_stmt_df.columns]

In [11]:
balance_sheet_df.head()

,symbol_bs,reportedCurrency_bs,cik_bs,fillingDate_bs,acceptedDate_bs,calendarYear_bs,period_bs,cashAndCashEquivalents_bs,shortTermInvestments_bs,cashAndShortTermInvestments_bs,netReceivables_bs,inventory_bs,otherCurrentAssets_bs,totalCurrentAssets_bs,propertyPlantEquipmentNet_bs,goodwill_bs,intangibleAssets_bs,goodwillAndIntangibleAssets_bs,longTermInvestments_bs,taxAssets_bs,otherNonCurrentAssets_bs,totalNonCurrentAssets_bs,otherAssets_bs,totalAssets_bs,accountPayables_bs,shortTermDebt_bs,taxPayables_bs,deferredRevenue_bs,otherCurrentLiabilities_bs,totalCurrentLiabilities_bs,longTermDebt_bs,deferredRevenueNonCurrent_bs,deferredTaxLiabilitiesNonCurrent_bs,otherNonCurrentLiabilities_bs,totalNonCurrentLiabilities_bs,otherLiabilities_bs,capitalLeaseObligations_bs,totalLiabilities_bs,preferredStock_bs,commonStock_bs,retainedEarnings_bs,accumulatedOtherComprehensiveIncomeLoss_bs,othertotalStockholdersEquity_bs,totalStockholdersEquity_bs,totalEquity_bs,totalLiabilitiesAndStockholdersEquity_bs,minorityInterest_bs,totalLiabilitiesAndTotalEquity_bs,totalInvestments_bs,totalDebt_bs,netDebt_bs,link_bs,finalLink_bs
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-03-31,SSY,USD,0000096793,2023-05-10,2023-05-10 16:40:35,2023,Q3,5382000,0,5382000,4394000,1787000,1741000,13304000,9341000,0,1182000,1182000,0,0,603000,11126000,0,24430000,1569000,375000,188000,469000,2264000,4677000,612000,0,0,342000,954000,0,987000,5631000,0,3516000,4431000,106000,10746000,18799000,18799000,24430000,0,24430000,0,987000,-4395000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-12-31,SSY,USD,0000096793,2023-02-14,2023-02-14 11:34:09,2023,Q2,5156000,0,5156000,6212000,1812000,1844000,15024000,9461000,0,1188000,1188000,0,0,496000,11145000,0,26169000,1876000,385000,171000,469000,2903000,5633000,699000,0,0,276000,975000,0,1054000,6608000,0,3516000,5193000,106000,10746000,19561000,19561000,26169000,0,26169000,0,1084000,-4072000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-09-30,SSY,USD,0000096793,2022-11-14,2022-11-14 13:14:19,2023,Q1,4951000,0,4951000,6447000,1842000,2166000,15406000,9595000,0,1195000,1195000,0,69000,561000,11420000,0,26826000,1831000,395000,2777000,469000,5468000,8163000,783000,0,69000,201000,1053000,0,1134000,9216000,0,3516000,3242000,106000,10746000,17610000,17610000,26826000,0,26826000,0,1178000,-3773000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-06-30,SSY,USD,0000096793,2022-09-28,2022-09-28 14:55:21,2022,Q4,6794000,0,6794000,6385000,1748000,1888000,16815000,9404000,0,1201000,1201000,0,0,523000,11128000,0,27943000,1347000,392000,2600000,519000,5433000,7691000,871000,0,69000,192000,1132000,0,1209000,8823000,0,3478000,4800000,106000,10736000,19120000,19120000,27943000,0,27943000,0,1263000,-5531000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...
2022-03-31,SSY,USD,0000096793,2022-05-16,2022-05-16 16:17:02,2022,Q3,7144000,0,7144000,8295000,1919000,5877000,19180000,9145000,0,1208000,1208000,0,0,424000,10777000,0,29957000,1351000,379000,2445000,521000,5242000,7493000,927000,0,0,320000,1247000,0,1306000,8740000,0,3478000,7165000,-162000,10736000,21217000,21217000,29957000,0,29957000,0,1306000,-5838000,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...

### Concatenate sources

In [67]:
type(engine)

sqlalchemy.engine.base.Engine

In [13]:
financial_info = pd.concat([balance_sheet_df, income_stmt_df], axis=1)

In [14]:
financial_info = financial_info.reset_index()
financial_info.head()

,date,symbol_bs,reportedCurrency_bs,cik_bs,fillingDate_bs,acceptedDate_bs,calendarYear_bs,period_bs,cashAndCashEquivalents_bs,shortTermInvestments_bs,cashAndShortTermInvestments_bs,netReceivables_bs,inventory_bs,otherCurrentAssets_bs,totalCurrentAssets_bs,propertyPlantEquipmentNet_bs,goodwill_bs,intangibleAssets_bs,goodwillAndIntangibleAssets_bs,longTermInvestments_bs,taxAssets_bs,otherNonCurrentAssets_bs,totalNonCurrentAssets_bs,otherAssets_bs,totalAssets_bs,accountPayables_bs,shortTermDebt_bs,taxPayables_bs,deferredRevenue_bs,otherCurrentLiabilities_bs,totalCurrentLiabilities_bs,longTermDebt_bs,deferredRevenueNonCurrent_bs,deferredTaxLiabilitiesNonCurrent_bs,otherNonCurrentLiabilities_bs,totalNonCurrentLiabilities_bs,otherLiabilities_bs,capitalLeaseObligations_bs,totalLiabilities_bs,preferredStock_bs,commonStock_bs,retainedEarnings_bs,accumulatedOtherComprehensiveIncomeLoss_bs,othertotalStockholdersEquity_bs,totalStockholdersEquity_bs,totalEquity_bs,totalLiabilitiesAndStockholdersEquity_bs,minorityInterest_bs,totalLiabilitiesAndTotalEquity_bs,totalInvestments_bs,totalDebt_bs,netDebt_bs,link_bs,finalLink_bs,revenue_is,costOfRevenue_is,grossProfit_is,grossProfitRatio_is,researchAndDevelopmentExpenses_is,generalAndAdministrativeExpenses_is,sellingAndMarketingExpenses_is,sellingGeneralAndAdministrativeExpenses_is,otherExpenses_is,operatingExpenses_is,costAndExpenses_is,interestIncome_is,interestExpense_is,depreciationAndAmortization_is,ebitda_is,ebitdaratio_is,operatingIncome_is,operatingIncomeRatio_is,totalOtherIncomeExpensesNet_is,incomeBeforeTax_is,incomeBeforeTaxRatio_is,incomeTaxExpense_is,netIncome_is,netIncomeRatio_is,eps_is,epsdiluted_is,weightedAverageShsOut_is,weightedAverageShsOutDil_is
0,2023-03-31,SSY,USD,0000096793,2023-05-10,2023-05-10 16:40:35,2023,Q3,5382000.0,0.0,5382000.0,4394000.0,1787000.0,1741000.0,13304000.0,9341000.0,0.0,1182000.0,1182000.0,0.0,0.0,603000.0,11126000.0,0.0,24430000.0,1569000.0,375000.0,188000.0,469000.0,2264000.0,4677000.0,612000.0,0.0,0.0,342000.0,954000.0,0.0,987000.0,5631000.0,0.0,3516000.0,4431000.0,106000.0,10746000.0,18799000.0,18799000.0,24430000.0,0.0,24430000.0,0.0,987000.0,-4395000.0,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...,11533000,6066000,5467000,0.474031,0,4656000,0,4656000,1585000,6241000,12307000,0,41000,414000,-360000,-0.031215,-774000,-0.067112,41000,-733000,-0.063557,-6000,-727000,-0.063037,-0.10,-0.10,7032000,7032000
1,2022-12-31,SSY,USD,0000096793,2023-02-14,2023-02-14 11:34:09,2023,Q2,5156000.0,0.0,5156000.0,6212000.0,1812000.0,1844000.0,15024000.0,9461000.0,0.0,1188000.0,1188000.0,0.0,0.0,496000.0,11145000.0,0.0,26169000.0,1876000.0,385000.0,171000.0,469000.0,2903000.0,5633000.0,699000.0,0.0,0.0,276000.0,975000.0,0.0,1054000.0,6608000.0,0.0,3516000.0,5193000.0,106000.0,10746000.0,19561000.0,19561000.0,26169000.0,0.0,26169000.0,0.0,1084000.0,-4072000.0,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...,14392000,5918000,8474000,0.588799,0,4793000,0,4793000,1641000,6434000,12352000,0,9000,385000,2425000,0.168496,2040000,0.141745,11000,2051000,0.142510,-1000,1951000,0.135561,0.28,0.28,7031000,7033000
2,2022-09-30,SSY,USD,0000096793,2022-11-14,2022-11-14 13:14:19,2023,Q1,4951000.0,0.0,4951000.0,6447000.0,1842000.0,2166000.0,15406000.0,9595000.0,0.0,1195000.0,1195000.0,0.0,69000.0,561000.0,11420000.0,0.0,26826000.0,1831000.0,395000.0,2777000.0,469000.0,5468000.0,8163000.0,783000.0,0.0,69000.0,201000.0,1053000.0,0.0,1134000.0,9216000.0,0.0,3516000.0,3242000.0,106000.0,10746000.0,17610000.0,17610000.0,26826000.0,0.0,26826000.0,0.0,1178000.0,-3773000.0,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...,11037000,5741000,5296000,0.479841,0,5448000,0,5448000,1461000,6909000,12650000,0,-4000,356000,-1257000,-0.113890,-1613000,-0.146145,69000,-1544000,-0.139893,-63000,-1481000,-0.134185,-0.21,-0.21,6983000,6983000
3,2022-06-30,SSY,USD,0000096793,2022-09-28,2022-09-28 14:55:21,2022,Q4,6794000.0,0.0,6794000.0,6385000.0,1748000.0,1888000.0,16815000.0,9404000.0,0.0,1201000.0,1201000.0,0.0,0.0,523000.0,11128000.0,0.0,27943000.0,1347000.0,392000.0,2600000.0,519000.0,5433000.0,7691000.0,871000.0,0.0,69000.0,192000.0,1132000.0,0.0,1209000.0,8823000.0,0.0,3478000.0,4800000.0,106000.0,10736000.0,19120000.0,19120000.0,27943000.0,0.0,27943000.0,0.0,1263000.0,-5531000.0,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...,9881000,5581000,4300000,0.435179,0,4916000,0,4916000,1595000,6511000,12092000,0,3000,462000,-1749000,-0.177006,-2211000,-0.223763,1000,-2210000,-0.223662,107000,-2317000,-0.234490,-0.33,-0.33,6945000,6945000
4,2022-03-31,SSY,USD,0000096793,2022-05-16,2022-05-16 16:17:02,2022,Q3,7144000.0,0.0,7144000.0,8295000.0,1919000.0,5877000.0,19180000.0,9145000.0,0.0,1208000.0,1208000.0,0.0,0.0,424000.0,10777000.0,0.0,29957000.0,1351000.0,379000.0,2445000.0,521000.0,5242000.0,7493000.0,927000.0,0.0,0.0,320000.0,1247000.0,0.0,1306000.0,8740000.0,0.0,3478000.0,7165000.0,-162000.0,10736000.0,21217000.0,21217000.0,29957000.0,0.0,29957000.0,0.0,1306000.0,-5838000.0,https://www.sec.gov/Archives/edgar/data/96793/...,https://www.sec.gov/Archives/edgar/data/96793/...,10527000,5315000,5212000,0.495108,0,4865000,0,4865000,1411000,6276000,11591000,0,-14000,384000,-680000,-0.064596,-1064000,-0.101073,105000,-959000,-0.091099,-25000,-934000,-0.088724,-0.13,-0.13,6954000,6954000

### Column types definition

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
pd.set_option("display.max_columns", 100)

In [2]:
db_uri = "postgresql://simonpalma:axionable@localhost:5432/yourdb"
engine = create_engine(db_uri)

In [64]:
with engine.connect() as connection:
    connection.execution_options(isolation_level="AUTOCOMMIT")
    connection.execute(text("""CREATE TABLE test_table (
        date date,
        symbol_bs character,
        reportedCurrency_bs character,
        cik_bs character,
        fillingDate_bs timestamp,
        calendarYear_bs integer,
        period_bs character,
        cashAndCashEquivalents_bs bigint,
        shortTermInvestments_bs bigint,
        cashAndShortTermInvestments_bs bigint,
        netReceivables_bs bigint,
        inventory_bs bigint,
        otherCurrentAssets_bs bigint,
        totalCurrentAssets_bs bigint,
        propertyPlantEquipmentNet_bs bigint,
        goodwill_bs bigint,
        intangibleAssets_bs bigint,
        goodwillAndIntangibleAssets_bs bigint,
        longTermInvestments_bs bigint,
        taxAssets_bs bigint,
        otherNonCurrentAssets_bs bigint,
        totalNonCurrentAssets_bs bigint,
        otherAssets_bs bigint,
        totalAssets_bs bigint,
        accountPayables_bs bigint,
        shortTermDebt_bs bigint,
        taxPayables_bs bigint,
        deferredRevenue_bs bigint,
        otherCurrentLiabilities_bs bigint,
        totalCurrentLiabilities_bs bigint,
        longTermDebt_bs bigint,
        deferredRevenueNonCurrent_bs bigint,
        deferredTaxLiabilitiesNonCurrent_bs bigint,
        otherNonCurrentLiabilities_bs bigint,
        totalNonCurrentLiabilities_bs bigint,
        otherLiabilities_bs bigint,
        capitalLeaseObligations_bs bigint,
        totalLiabilities_bs bigint,
        preferredStock_bs bigint,
        commonStock_bs bigint,
        retainedEarnings_bs bigint,
        accumulatedOtherComprehensiveIncomeLoss_bs bigint,
        othertotalStockholdersEquity_bs bigint,
        totalStockholdersEquity_bs bigint,
        totalEquity_bs bigint,
        totalLiabilitiesAndStockholdersEquity_bs bigint,
        minorityInterest_bs bigint,
        totalLiabilitiesAndTotalEquity_bs bigint,
        totalInvestments_bs bigint,
        totalDebt_bs bigint,
        netDebt_bs bigint,
        link_bs varchar,
        finalLink_bs varchar,
        revenue_is bigint,
        costOfRevenue_is bigint,
        grossProfit_is bigint,
        grossProfitRatio_is integer,
        researchAndDevelopmentExpenses_is bigint,
        generalAndAdministrativeExpenses_is bigint,
        sellingAndMarketingExpenses_is bigint,
        sellingGeneralAndAdministrativeExpenses_is bigint,
        otherExpenses_is bigint,
        operatingExpenses_is bigint,
        costAndExpenses_is bigint,
        interestIncome_is bigint,
        interestExpense_is bigint,
        depreciationAndAmortization_is bigint,
        ebitda_is bigint,
        ebitdaratio_is integer,
        operatingIncome_is bigint,
        operatingIncomeRatio_is integer,
        totalOtherIncomeExpensesNet_is bigint,
        incomeBeforeTax_is bigint,
        incomeBeforeTaxRatio_is integer,
        incomeTaxExpense_is bigint,
        netIncome_is bigint,
        netIncomeRatio_is integer,
        eps_is integer,
        epsdiluted_is integer,
        weightedAverageShsOut_is bigint,
        weightedAverageShsOutDil_is bigint)""")
    )
    
    financial_info.to_sql(name="test_table", con=connection, if_exists="replace", index=False)

In [57]:
query = "SELECT * FROM financial_stmts;"
engine = create_engine(db_uri)
connection = engine.connect()
df = pd.read_sql(query, con=engine)
connection.close()

In [58]:
df.shape

(250, 82)

In [3]:
query = "DROP TABLE financial_stmts;"
#engine = create_engine(db_uri)
with engine.connect() as connection:
    connection.execution_options(isolation_level="AUTOCOMMIT")
    connection.execute(text(query))